// @ts-check
// Slugs remain stable; labels are Japanese-first for the default locale.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  mainSidebar: [
    {
      type: 'category',
      label: 'はじめに',
      link: { type: 'doc', id: 'getting-started/index' },
      collapsed: false,
      items: [
        { type: 'doc', id: 'getting-started/install', label: 'インストール' },
        { type: 'doc', id: 'getting-started/first-prompt', label: '最初のプロンプト' },
        { type: 'doc', id: 'getting-started/clients', label: 'MCPクライアント' },
      ],
    },
    {
      type: 'category',
      label: 'ガイド',
      collapsed: false,
      items: [
        { type: 'doc', id: 'guides/uv-setup', label: 'uvセットアップ' },
        { type: 'doc', id: 'guides/claude-code-cli', label: 'Claude Code CLI' },
        { type: 'doc', id: 'guides/client-configurators', label: 'クライアント設定' },
        { type: 'doc', id: 'guides/multi-instance', label: '複数Unityインスタンス' },
        { type: 'doc', id: 'guides/tool-groups', label: 'ツールグループ' },
        { type: 'doc', id: 'guides/cli', label: 'CLI' },
        { type: 'doc', id: 'guides/cli-examples', label: 'CLI使用例' },
        { type: 'doc', id: 'guides/custom-tools', label: 'カスタムツール' },
        { type: 'doc', id: 'guides/remote-server-auth', label: 'リモートサーバー認証' },
        { type: 'doc', id: 'guides/roslyn', label: 'Roslyn' },
        { type: 'doc', id: 'guides/troubleshooting', label: 'トラブルシューティング' },
      ],
    },
    { type: 'doc', id: 'failures', label: '2026 エラー情報' },
    { type: 'doc', id: 'community-practice', label: 'VRChat / Unity 実践記事' },
    {
      type: 'category',
      label: 'リファレンス',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'ツール',
          link: { type: 'doc', id: 'reference/tools/index' },
          items: [{ type: 'autogenerated', dirName: 'reference/tools' }],
        },
        {
          type: 'doc',
          id: 'reference/resources/index',
          label: 'リソース',
        },
        { type: 'doc', id: 'reference/cli', label: 'CLIリファレンス' },
        { type: 'doc', id: 'reference/manifest', label: 'Manifest' },
      ],
    },
    {
      type: 'category',
      label: 'アーキテクチャ',
      collapsed: true,
      items: [
        { type: 'doc', id: 'architecture/transports', label: '通信方式' },
        { type: 'doc', id: 'architecture/instance-routing', label: 'インスタンスルーティング' },
        { type: 'doc', id: 'architecture/python-layers', label: 'Pythonレイヤー' },
        { type: 'doc', id: 'architecture/unity-compat', label: 'Unity互換性' },
        { type: 'doc', id: 'architecture/remote-auth', label: 'リモート認証' },
        { type: 'doc', id: 'architecture/telemetry', label: 'テレメトリ' },
        { type: 'doc', id: 'architecture/manage-physics', label: '物理操作' },
        { type: 'doc', id: 'architecture/project-roadmap', label: 'プロジェクトロードマップ' },
        { type: 'doc', id: 'architecture/roadmap', label: 'ロードマップ' },
        { type: 'doc', id: 'architecture/external-analytics', label: '外部分析' },
      ],
    },
    {
      type: 'category',
      label: 'コントリビューション',
      collapsed: true,
      items: [
        { type: 'doc', id: 'contributing/dev-setup', label: '開発環境' },
        { type: 'doc', id: 'contributing/testing', label: 'テスト' },
        { type: 'doc', id: 'contributing/releases', label: 'リリース手順' },
        { type: 'doc', id: 'contributing/docs', label: 'ドキュメント' },
      ],
    },
    {
      type: 'category',
      label: '移行ガイド',
      collapsed: true,
      items: [
        { type: 'doc', id: 'migrations/v5', label: 'v5への移行' },
        { type: 'doc', id: 'migrations/v6', label: 'v6への移行' },
        { type: 'doc', id: 'migrations/v8', label: 'v8への移行' },
        { type: 'doc', id: 'migrations/v10', label: 'v10への移行' },
      ],
    },
    { type: 'doc', id: 'releases', label: 'リリース履歴' },
  ],
};

export default sidebars;
